# pin to ubuntu 14.04 trusty tahr otherwise we end up with an outdated OpenSSL 1.0.1 14 Mar 2012 :/
dist: trusty
language: python
python:
#  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nosexcover
  - python setup.py install
# command to run tests
script:
# unittests
  - python setup.py nosetests --with-xcoverage --cover-package=scapy_ssl_tls --cover-html --cover-branch --xcoverage-file=cover/cobertura.xml
# integration against external services
  - python tests/integration_external.py
